name: Build Python 3.13.7 (macOS aarch64 with clang)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "build.sh"
      - ".github/workflows/build-python-3.13.yml"

jobs:
  build-macos-aarch64:
    runs-on: macos-14  # Apple Silicon (aarch64)

    env:
      CC: clang
      CXX: clang++
      LD: clang
      AR: llvm-ar
      RANLIB: llvm-ranlib
      NM: llvm-nm
      OBJDUMP: llvm-objdump
      STRIP: llvm-strip
      CFLAGS: "-O3 -fPIC"
      LDFLAGS: "-fuse-ld=lld"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install \
            pkg-config gdbm xz zlib bzip2 sqlite \
            openssl readline libffi ncurses tk llvm

      - name: Fetch Termux patches & subpackages
        run: |
          mkdir -p patches
          mkdir -p subpackages
          base_url="https://raw.githubusercontent.com/termux/termux-packages/master/packages/python"

          # Download patches
          for i in $(seq -w 0001 0010); do
            url=$(curl -sSL https://api.github.com/repos/termux/termux-packages/contents/packages/python | grep -o "\"${i}-[^\"]*\.patch\"" | head -n1 | tr -d '"')
            if [ -n "$url" ]; then
              curl -sSL "$base_url/$url" -o "patches/$url"
            fi
          done

          # Download subpackage scripts
          curl -sSL "$base_url/python-ensurepip-wheels.subpackage.sh" -o subpackages/python-ensurepip-wheels.subpackage.sh
          curl -sSL "$base_url/python-tkinter.subpackage.sh" -o subpackages/python-tkinter.subpackage.sh

      - name: Apply patches
        run: |
          for p in patches/*.patch; do
            [ -f "$p" ] && patch -p1 < "$p" || true
          done

      - name: Run build.sh (force clang, aarch64)
        run: |
          chmod +x ./build.sh
          ./build.sh ci aarch64-linux-android

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-3.13.7-aarch64-clang
          path: output/**
          
