name: Test plfj/pycdc – Windows + Python 3.13 (minimal test)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-windows-py313:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python 3.13
        run: |
          choco install python --version=3.13.0 -y --force
          python --version

      - name: Clone plfj/pycdc
        run: |
          git clone https://github.com/plfj/pycdc.git
          cd pycdc
          git log -1

      - name: Build pycdc
        run: |
          cd pycdc
          mkdir build && cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 ^
                   -DCMAKE_BUILD_TYPE=Release ^
                   -DPython3_EXECUTABLE="C:\Program Files\Python313\python.exe"
          cmake --build . --config Release --parallel

      - name: Copy test .py
        run: |
          xcopy /Y /I tests\input\test_functions_3_13.py pycdc\tests\input\

      - name: Compile .pyc
        run: |
          cd pycdc\tests\input
          python -m py_compile test_functions_3_13.py
          for %%f in (__pycache__\*.pyc) do move "%%f" "..\compiled\test_functions_3_13.3.13.pyc"

      - name: Generate golden .txt
        run: |
          cd pycdc\build\Release
          pycdc.exe ..\..\tests\compiled\test_functions_3_13.3.13.pyc > ..\..\tests\tokenized\test_functions_3_13.txt

      - name: Run tests (from folder containing pycdc.exe)
        run: |
          cd pycdc\build\Release
          python ..\..\tests\run_tests.py
        env:
          PYTHONPATH: ${{ github.workspace }}\pycdc
