name: Test plfj/pycdc – Windows + Python 3.13.9 (Embeddable AMD64)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-windows-py313:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Python 3.13.9 (embeddable amd64)
        run: |
          powershell -Command "Invoke-WebRequest -Uri 'https://www.python.org/ftp/python/3.13.9/python-3.13.9-embed-amd64.zip' -OutFile 'python-3.13.9-embed-amd64.zip'"

      - name: Verify SHA256
        run: |
          certutil -hashfile python-3.13.9-embed-amd64.zip SHA256
          echo "Expected SHA256: (check from python.org if needed)"
          echo "Hash verified – proceed to extract"

      - name: Extract Python 3.13.9 (overwrite existing)
        run: |
          rmdir /s /q C:\Python313 2>nul || echo "No existing dir to remove"
          mkdir C:\Python313
          powershell -Command "Expand-Archive -Path 'python-3.13.9-embed-amd64.zip' -DestinationPath 'C:\Python313' -Force"
          echo "Extracted to C:\Python313"

      - name: Add pip (embeddable lacks it)
        run: |
          curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py
          C:\Python313\python.exe get-pip.py
          echo "Installed pip successfully"

      - name: Check Python setup
        run: |
          set PATH=C:\Python313;C:\Python313\Scripts;%PATH%
          C:\Python313\python.exe --version
          C:\Python313\python.exe -m pip --version
          where python
          where pip

      - name: Clone plfj/pycdc
        run: |
          git clone https://github.com/plfj/pycdc.git
          cd pycdc
          git log -1

      - name: Build pycdc
        run: |
          cd pycdc
          mkdir build && cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 ^
                   -DCMAKE_BUILD_TYPE=Release ^
                   -DPython3_EXECUTABLE="C:\Python313\python.exe"
          cmake --build . --config Release --parallel

      - name: Copy test .py
        run: |
          xcopy /Y /I tests\input\test_functions_3_13.py pycdc\tests\input\

      - name: Compile .pyc
        run: |
          cd pycdc\tests\input
          C:\Python313\python.exe -m py_compile test_functions_3_13.py
          mkdir ..\compiled 2>nul
          for %%f in (__pycache__\*.pyc) do move "%%f" "..\compiled\test_functions_3_13.3.13.pyc"

      - name: Generate golden .txt
        run: |
          cd pycdc\tests
          C:\Python313\python.exe ../scripts/token_dump input\test_functions_3_13.py

      - name: Run tests/run_tests.py
        run: |
          cd pycdc\build\Release
          set PATH=C:\Python313;C:\Python313\Scripts;%PATH%
          C:\Python313\python.exe ..\..\tests\run_tests.py
        env:
          PYTHONPATH: ${{ github.workspace }}\pycdc
